In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
# Load the cleaned dataset
df = pd.read_csv("../Data/kickstarter_cleaned.csv")
df.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,duration
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55

In [5]:
#Checking unique values in the state column
df['state'].unique()

array(['failed', 'canceled', 'successful', 'suspended'], dtype=object)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372066 entries, 0 to 372065
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                372066 non-null  int64
 1   name              372062 non-null  object
 2   category          372066 non-null  object
 3   main_category     372066 non-null  object
 4   currency          372066 non-null  object
 5   deadline          372066 non-null  object
 6   goal              372066 non-null  float64
 7   launched          372066 non-null  object
 8   pledged           372066 non-null  float64
 9   state             372066 non-null  object
 10  backers           372066 non-null  int64
 11  country           372066 non-null  object
 12  usd_pledged_real  372066 non-null  float64
 13  usd_goal_real     372066 non-null  float64
 14  duration          372066 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 42.6+ MB

In [7]:
df.isna().sum()

ID                  0
name                4
category            0
main_category       0
currency            0
deadline            0
goal                0
launched            0
pledged             0
state               0
backers             0
country             0
usd_pledged_real    0
usd_goal_real       0
duration            0
dtype: int64

In [8]:
df['state_binary'] = df['state'].replace({
    'successful': 1,
    'failed': 0,
    'canceled': 0,
    'suspended': 0
})

df['state_binary'].value_counts(normalize=True)

C:\Users\27025\AppData\Local\Temp\ipykernel_37596\3775006814.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['state_binary'] = df['state'].replace({

state_binary
0    0.640249
1    0.359751
Name: proportion, dtype: float64

In [9]:
df.dropna(inplace=True)

In [10]:
df.isna().sum()

ID                  0
name                0
category            0
main_category       0
currency            0
deadline            0
goal                0
launched            0
pledged             0
state               0
backers             0
country             0
usd_pledged_real    0
usd_goal_real       0
duration            0
state_binary        0
dtype: int64

In [11]:
df.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,duration,state_binary
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58,0
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59,0
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44,0
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29,0
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55,0

In [16]:
X.dtypes

category          object
main_category     object
currency          object
deadline          object
goal             float64
launched          object
country           object
usd_goal_real    float64
duration           int64
dtype: object

In [17]:
# Convert launched/deadline to datetime

df["launched"] = pd.to_datetime(df["launched"], errors="coerce")
df["deadline"] = pd.to_datetime(df["deadline"], errors="coerce")

In [18]:
df["launch_year"] = df["launched"].dt.year
df["launch_month"] = df["launched"].dt.month
df["launch_weekday"] = df["launched"].dt.weekday

In [19]:
df = df.drop(columns=["launched", "deadline"])

In [20]:
drop_cols = [
    "ID", "name", "state",
    "pledged", "usd_pledged_real",
    "backers"
]

In [21]:
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

In [22]:
if "goal" in df.columns and "usd_goal_real" in df.columns:
    df = df.drop(columns=["goal"])

In [23]:
X = df.drop("state_binary", axis=1)
y = df["state_binary"]

In [32]:
X.dtypes

category           object
main_category      object
currency           object
country            object
usd_goal_real     float64
duration            int64
launch_year         int32
launch_month        int32
launch_weekday      int32
dtype: object

In [24]:
categorical_features = ["category", "main_category", "currency", "country"]
categorical_features = [c for c in categorical_features if c in X.columns]

numeric_features = X.drop(columns=categorical_features).columns.tolist()

In [25]:
print("Categorical features:", categorical_features)
print("Numeric features:", numeric_features)

Categorical features: ['category', 'main_category', 'currency', 'country']
Numeric features: ['usd_goal_real', 'duration', 'launch_year', 'launch_month', 'launch_weekday']

In [26]:
X_encoded = pd.get_dummies(X, columns=categorical_features, drop_first=True)

In [35]:
X_encoded.head()

,usd_goal_real,duration,launch_year,launch_month,launch_weekday,category_Academic,category_Accessories,category_Action,category_Animals,category_Animation,...,country_IT,country_JP,country_LU,country_MX,country_NL,country_NO,country_NZ,country_SE,country_SG,country_US
0,1533.95,58,2015,8,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,30000.00,59,2017,9,5,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,45000.00,44,2013,1,5,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,5000.00,29,2012,3,5,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,19500.00,55,2015,7,5,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [28]:
print("Train shape:", X_train.shape, "Test shape:", X_test.shape)

Train shape: (297649, 211) Test shape: (74413, 211)

In [29]:
scaler = StandardScaler()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

In [30]:
X_train_scaled[numeric_features] = scaler.fit_transform(X_train[numeric_features])
X_test_scaled[numeric_features] = scaler.transform(X_test[numeric_features])

In [31]:
df.head()

,category,main_category,currency,country,usd_goal_real,duration,state_binary,launch_year,launch_month,launch_weekday
0,Poetry,Publishing,GBP,GB,1533.95,58,0,2015,8,1
1,Narrative Film,Film & Video,USD,US,30000.00,59,0,2017,9,5
2,Narrative Film,Film & Video,USD,US,45000.00,44,0,2013,1,5
3,Music,Music,USD,US,5000.00,29,0,2012,3,5
4,Film & Video,Film & Video,USD,US,19500.00,55,0,2015,7,5

In [33]:
X_train_scaled.to_csv("X_train_preprocessed.csv", index=False)
X_test_scaled.to_csv("X_test_preprocessed.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)